### ISSUE TITLE
Project membership upsert does not work as expected

### ISSUE THREAD

**Issue by tmcadam** [ACCESS-NRI/ncigrafana#8]
Upsert in project membership causes an error.

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "projectmembership_unique"
DETAIL:  Key (project_id, system_id, date)=(88, 4, 2023-02-26) already exists.

[SQL: INSERT INTO "ProjectMembership" (project_id, system_id, date, members, members_count) VALUES (%(project_id)s, %(system_id)s, %(date)s, %(members)s, %(members_count)s) RETURNING "ProjectMembership".id]
[parameters: {'project_id': 88, 'system_id': 4, 'date': datetime.date(2023, 2, 26), 'members': 've4896,aph502,hj1810', 'members_count': 3}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Comment by aidanheerdegen** [comment]
It's good to include the text of the error so it can be found if it recurs.

**Comment by tmcadam** [comment]
@Aidan I've added the error text. 

Interestingly, if running the test I created without this fix, it doesn't raise this integrity error, but the assertation fails anyway (4!=3), as the data hasn't been updated. I think this is due to the tests running against sqllite, while production code runs against postgresql, they must have slightly different upsert behavior.

**Comment by aidanheerdegen** [comment]
Thanks, and yeah super useful detail of the failure mode.
